export { execute, query } from "./client";
export type { Row } from "./client";
export { initDb } from "./schema";
export { getCached, getBatchCached, setCached, touchCached, deleteCached } from "./metadata.repo";
export {
  getFollowedSeriesPage,
  getFollowedSeriesRow,
  getFollowedRevision,
  onFollowedChanged,
  notifyFollowedChanged,
  followSeries,
  unfollowSeries,
  updateFollowedSeriesCover,
  getReadingProgress,
  getProgressRevision,
  onProgressChanged,
  notifyProgressChanged,
  setReadingProgress,
  getProgressForSeries,
  addHistory,
  removeHistory,
  removeHistoryBatch,
  clearHistory,
  getHistoryPage,
  getHistoryMap,
  getHistoryPermalinks,
  getHistoryRevision,
  onHistoryChanged,
  notifyHistoryChanged,
  getBookmarksPage,
  getBookmark,
  getBookmarkPermalinks,
  getBookmarksRevision,
  onBookmarksChanged,
  notifyBookmarksChanged,
  addBookmark,
  removeBookmark,
  removeBookmarksBatch,
} from "./library.repo";
export {
  getCachedPages,
  setCachedPage,
  getCachedPageCounts,
  getCacheOverviewStats,
  getCachedSeriesGroups,
  clearCachedGroupPages,
  clearAllCachedPages,
  clearAllCachedCovers,
  clearAllCacheStorage,
  getFullyCachedChapters,
  getFullyCachedChapterPermalinks,
  pruneOldestReadCachedPages,
} from "./cache.repo";
export type { FullyCachedChapterRow, CachePruneResult } from "./cache.repo";
export {
  getBlacklistedTags,
  addBlacklistedTag,
  removeBlacklistedTag,
  getBlacklistedSeries,
  addBlacklistedSeries,
  removeBlacklistedSeries,
  isSeriesBlacklisted,
  getBlacklistRevision,
  onBlacklistChanged,
  initBlacklistCache,
  isItemBlacklisted,
  getBlacklistMode,
  setBlacklistMode,
} from "./blacklist.repo";
export type { BlacklistedTag, BlacklistedSeries, BlacklistCheckResult, BlacklistMode } from "../types/blacklist";
export {
  getCollections,
  getCollectionsRevision,
  onCollectionsChanged,
  notifyCollectionsChanged,
  getCollectionById,
  createCollection,
  deleteCollection,
  getCollectionItems,
  addItemToCollection,
  removeItemFromCollection,
  getItemCollectionIds,
  toggleItemInCollection,
  updateCollectionItemCover,
} from "./collections.repo";
export { searchDirectoryEntries, saveDirectoryEntries, suggestDirectoryEntries, saveSuggestEntries } from "./directory.repo";
export {
  getDbFileStats,
  getDbTableCounts,
  getDbStats,
  wipeDatabase,
  backupDatabase,
  restoreDatabaseFromPath,
} from "./db.manage";
export { getLocalSeries, getLocalSeriesByPermalink } from "./local.repo";
export type { LocalSeriesRow } from "./local.repo";
export type { DbStats, DbFileStats, DbTableCounts } from "./db.manage";
export type {
  CachedMetadata,
  FollowedSeriesRow,
  FollowedSeriesPageResult,
  ReadingProgressRow,
  SeriesProgressRow,
  HistoryRow,
  HistoryPageResult,
  BookmarkRow,
  BookmarkPageResult,
  CachedPageRow,
  ChapterCacheCount,
  CacheOverviewStats,
  CachedSeriesGroup,
  CollectionRow,
  CollectionItemRow,
  CollectionItemKind,
} from "../types/db";
